### ISSUE TITLE
ArrayIndexOutOfBoundsException at ParseEnvironment.java:122 (check-allsat)

### ISSUE THREAD

**Issue by rainoftime** [ultimate-pa/smtinterpol#106]
Hi, for the following formula,

smtinterpol commit
cb90e74
~~~~
 Unexpected Exception: java.lang.ArrayIndexOutOfBoundsException: 4
 Exception in thread "main" de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: java.lang.ArrayIndexOutOfBoundsException: 4
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:122)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:98)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:35)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:165)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine$AllSatIterator.next(DPLLEngine.java:1808)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine$AllSatIterator.next(DPLLEngine.java:1769)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SExpression.convertSexp(SExpression.java:58)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SExpression.toString(SExpression.java:82)
        at java.lang.String.valueOf(String.java:2994)
        at java.io.PrintWriter.println(PrintWriter.java:754)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.printResponse(ParseEnvironment.java:168)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:3154)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:1317)
        at com.github.jhoenicke.javacup.runtime.LRParser.parse(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:119)
        ... 3 more

~~~~

**Comment by rainoftime** [comment]
Another formula
~~~~
(set-logic QF_BV)
(declare-fun notes () (_ BitVec 4))
(declare-fun | | () (_ BitVec 4))
(declare-fun || () (_ BitVec 4))
(check-sat)
~~~~
