### ISSUE TITLE
(proof) Assertion error at CCTerm.java:311 on AUFLIA formula

### ISSUE THREAD

**Issue by rainoftime** [ultimate-pa/smtinterpol#114]
Hi, for the following instance,
[311.txt](https://github.com/ultimate-pa/smtinterpol/files/5249136/311.txt)

SMTInterpol 6c2e28f88e
~~~~
xception in thread "main" java.lang.AssertionError
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCTerm.propagateSharedEquality(CCTerm.java:311)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCTerm.share(CCTerm.java:282)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CClosure.addSharedTerm(CClosure.java:784)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.share(Clausifier.java:1020)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.shareLATerm(Clausifier.java:1028)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.createLinVar(Clausifier.java:1141)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.createMutableAffinTerm(Clausifier.java:1151)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.createLeq0(Clausifier.java:2116)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.access$1600(Clausifier.java:93)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier$CollectLiteral.perform(Clausifier.java:606)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.run(Clausifier.java:1937)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.addFormula(Clausifier.java:2005)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.assertTerm(SMTInterpol.java:678)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:2853)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:1317)
        at com.github.jhoenicke.javacup.runtime.LRParser.parse(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:119)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:98)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:35)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:165)

~~~~

**Comment by jhoenicke** [comment]
The equality that should be propagated here was created earlier but not propagated when the equivalence classes merged.

This happend, because it was merged by a congruence step in backtrackComplete.  The equality literal was added to pending literals, but then never propagated, as no quickcheck was started.  Instead the next backtrackComplete happened (in clearAssumption) and removed the pending literal, even though the merge was not undone.

Probably we need to not clear mPending in backtrackComplete, but instead only remove those that are no longer equivalent.

**Comment by jhoenicke** [comment]
I changed the code in d208e931d9f8b0b577ab116fd5d39d869a5c5505 to not call backtrackComplete unless something was backtracked.  This fixes this problem, but there may still be problems with pop() or clearAssumptions if something was backtracked.

**Comment by rainoftime** [comment]
Fixed.
