### ISSUE TITLE
Pushing solver before adding a quantified formula leads to AssertionError

### ISSUE THREAD

**Issue by sallaigy** [ultimate-pa/smtinterpol#144]
Hello,

The following script crashes SMTInterpol with an AssertionError:

```
(set-logic LIA)
(push 4)
(assert (exists ((x Bool)) true))
(reset-assertions)
(assert (exists ((x Bool)) true))
```

In order to reproduce the issue you need to push the solver before introducing the first quantified formula, then reset the solver, then add a quantified formula again.

The stack for the exception:

```
Exception in thread "main" java.lang.AssertionError
	at de.uni_freiburg.informatik.ultimate.logic.Theory.declareInternalFunctionFactory(Theory.java:1447)
	at de.uni_freiburg.informatik.ultimate.logic.Theory.declareInternalPolymorphicFunction(Theory.java:610)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.ProofRules.setupTheory(ProofRules.java:174)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.ProofRules.<init>(ProofRules.java:142)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.convertQuantifiedSubformula(Clausifier.java:1267)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.access$800(Clausifier.java:106)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier$AddAsAxiom.perform(Clausifier.java:348)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.run(Clausifier.java:2230)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.addFormula(Clausifier.java:2301)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.assertTerm(SMTInterpol.java:658)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:2869)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:1333)
	at com.github.jhoenicke.javacup.runtime.LRParser.parse(Unknown Source)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:120)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:99)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:35)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:182)
```

After some debugging into the internals of the solver, it seems that some auxiliary declarations (`..Proof` and `..choose`) end up being inserted on the freshly pushed scope, and when the solver is reset, some of these get popped out, leading to an inconsistent state, which leads to a crash when the next quantified formula is added.

**Comment by jhoenicke** [comment]
Looks like it's easy to fix.
