### ISSUE TITLE
AssertionError: Not a unit clause

### ISSUE THREAD

**Issue by PhilippWendler** [ultimate-pa/smtinterpol#21]
The [queries with arrays in this gist](https://gist.github.com/PhilippWendler/f3abd1804b656d4baa6e75597b46b7e0) produce stack traces like the following one:
```
java.lang.AssertionError: Not a unit clause: diva_dadapter_request::e@5 == diva_dadapter_request::e@4 in [!(*unsigned_char@8 == (store *unsigned_char@7 (+ |diva_dadapter_request::e@4| 1) 255)), !(*unsigned_char@7 == *unsigned_char@5), diva_dadapter_request::e@5 == diva_dadapter_request::e@4, !(*unsigned_char@8 == *unsigned_char@7), !(*unsigned_char@7 == (store *unsigned_char@6 (+ |diva_dadapter_request::e@5| 1) 255)), !(*unsigned_char@6 == (store *unsigned_char@5 (+ |diva_dadapter_request::e@4| 1) 7)), (select (store *unsigned_char@5 (+ |diva_dadapter_request::e@4| 1) 7) (+ |diva_dadapter_request::e@4| 1)) == (select (store *unsigned_char@5 (+ |diva_dadapter_request::e@4| 1) 255) (+ |diva_dadapter_request::e@4| 1))]
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.checkUnitClause(DPLLEngine.java:843)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.getExplanation(DPLLEngine.java:774)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.computeRedundancy(DPLLEngine.java:803)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.explainConflict(DPLLEngine.java:681)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.explain(DPLLEngine.java:749)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.solve(DPLLEngine.java:1079)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine$AllSatIterator.hasNext(DPLLEngine.java:1635)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.printResponse(ParseEnvironment.java:205)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:2181)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:853)
        at java_cup.runtime.LRParser.parse(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:129)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:114)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:40)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:182)
```

I have more examples for this problem, but this should hopefully be the two smallest ones.

**Comment by PhilippWendler** [comment]
Sorry, I messed up with GitHub, but luckily I also found another smaller query with the same problem: https://gist.github.com/PhilippWendler/f3abd1804b656d4baa6e75597b46b7e0#file-smtinterpol-assertionerror-not-a-unit-clause-0-smt2

The other two examples are https://gist.github.com/PhilippWendler/f3abd1804b656d4baa6e75597b46b7e0/d18266f666043cba10ef139d235230c6df134a77#file-smtinterpol-assertionerror-not-a-unit-clause-smt2 and https://gist.github.com/PhilippWendler/f3abd1804b656d4baa6e75597b46b7e0/8a07d061f1cad544fe3e6c6df73d60d079c19b1f#file-smtinterpol-assertionerror-not-a-unit-clause-2-smt2

**Comment by jhoenicke** [comment]
Which version are you using? java -jar smtinterpol.jar -version

**Comment by PhilippWendler** [comment]
Oh sorry, I mixed up the various query files and the different SMTInterpol versions I tested them against. The file https://gist.githubusercontent.com/PhilippWendler/f3abd1804b656d4baa6e75597b46b7e0/raw/8a07d061f1cad544fe3e6c6df73d60d079c19b1f/smtinterpol-AssertionError-not-a-unit-clause-2.smt2 produces this assertion even with the newest version 2.1-254-geb3b2f8-comp, the other queries only produce it with an older version.

**Comment by jhoenicke** [comment]
I can reproduce it now.  Bug seems to be in ArrayTheory and has to do with choosing wrong equality, e.g. (= (+ A 5) (+ B 5))  vs. (= A B)

**Comment by jhoenicke** [comment]
This was related to issue #14.  The same function to create equalities was used in WeakCongruencePath to build the lemma.  I now call the function from ArrayTheory there.
