### ISSUE TITLE
Another AssertionError with check-sat-assuming

### ISSUE THREAD

**Issue by kfriedberger** [ultimate-pa/smtinterpol#40]
The following snipped causes SMTInterpol to fail with an AssertionError:

<pre>
SMTInterpol env = new SMTInterpol(new DefaultLogger(), () -> false);
env.setLogic(Logics.QF_AUFLIRA);
env.declareFun("A", new Sort[] {}, env.getTheory().getBooleanSort());
Term[] terms = new Term[] {env.term("A")};
env.checkSatAssuming(terms);
env.checkSat();
env.checkSatAssuming(terms);
</pre>

Stacktrace:
<pre>
Exception in thread "main" java.lang.AssertionError
at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.assume(DPLLEngine.java:1877)
at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.checkSatAssuming(SMTInterpol.java:492)
</pre>

Strangely, the corresponding SMTlib-input does **not trigger** the problem:
<pre>
(set-logic QF_AUFLIRA)
(declare-fun A () Bool)
(check-sat-assuming (A))
(check-sat)
(check-sat-assuming (A))
</pre>

This issue might be related to #29.

**Comment by kfriedberger** [comment]
This issue seems to not be fixed until today. Is there any progress?
