### ISSUE TITLE
Assertion on Interpolation in Branch `quantifiers`

### ISSUE THREAD

**Issue by kfriedberger** [ultimate-pa/smtinterpol#46]
The [appended smt2-file](https://github.com/ultimate-pa/smtinterpol/files/3584396/smtquery.000.txt) causes an assertion when computing interpolants.

I used the latest version from the branch `quantifiers` and executed:
<pre>
java -ea -jar dist/smtinterpol-2.5-532-g5379eb3.jar -q smtquery.000.txt
</pre>

The result is an Assertion:
<pre>
Exception in thread "main" java.lang.AssertionError
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator$MixedLAInterpolator.convert(Interpolator.java:923)
	at de.uni_freiburg.informatik.ultimate.logic.TermTransformer.cacheConvert(TermTransformer.java:131)
	at de.uni_freiburg.informatik.ultimate.logic.TermTransformer.access$000(TermTransformer.java:42)
	at de.uni_freiburg.informatik.ultimate.logic.TermTransformer$Convert.walk(TermTransformer.java:79)
	at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:115)
	at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:106)
	at de.uni_freiburg.informatik.ultimate.logic.TermTransformer.transform(TermTransformer.java:253)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.mixedPivotLA(Interpolator.java:1124)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.combine(Interpolator.java:371)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.access$200(Interpolator.java:60)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator$CombineInterpolants.walk(Interpolator.java:158)
	at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:115)
	at de.uni_freiburg.informatik.ultimate.logic.NonRecursive.run(NonRecursive.java:106)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.interpolate(Interpolator.java:238)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.getInterpolants(Interpolator.java:215)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:863)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:2330)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:1146)
	at com.github.jhoenicke.javacup.runtime.LRParser.parse(Unknown Source)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:155)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:133)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:37)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:180)
</pre>

The branch is important for us, because the assertion also happens in the latest Maven-release, which was build from `2.5-515-g2765bdd2` that is part of the history of this branch.
We use that version from Maven in CPAchecker (see the [corresponding issue](https://gitlab.com/sosy-lab/software/cpachecker/issues/609)).
Please either fix the assertion in the branch `quantifiers` or release a new Maven-build from the master-branch.

**Comment by danieldietsch** [comment]
The issue in CPAChecker is not visible for us.

**Comment by kfriedberger** [comment]
The issue in CPAchecker is just mentioning the CPAchecker-internal commit where SMTInterpol was updated and some examples with assertions. The example given here is one of them, formatted as SMTlib2 and already reduced and simplified. 
PS: We will hopefully make our issues publicly available soon.

**Comment by jhoenicke** [comment]
I had to remove one `(pop 1)` then I can reproduce the bug.  It has an easy fix. I'll make a new version, when I tested the change.

**Comment by kfriedberger** [comment]
Thanks for the quick response.

Just out of interest: Which `pop` did you remove?
I get the assertion in version 5379eb3 directly with the given file, without removing anything.
I just checked with a fresh checkout and clean build of SMTInterpol.

**Comment by jhoenicke** [comment]
The pop error is:

```smt2
(error "smtquery000.txt:6212:5: Not enough levels on assertion stack")
```

**Comment by kfriedberger** [comment]
Ah, I found it. That mistake must have happened during the simplification from the much larger input file :-)

**Comment by jhoenicke** [comment]
New version of the quantifier branch `2.5-533-ga4ba1513` released on maven.
