### ISSUE TITLE
AssertionError in DPLLEngine.setLiteral

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/smtinterpol#60]
Attached script throws assertion error when assertions are enabled (``java -ea -jar smtinterpol-2.5-638-g686b1653.jar``).

Stack trace: 
```
Exception in thread "main" java.lang.AssertionError
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.setLiteral(DPLLEngine.java:440)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.propagateTheories(DPLLEngine.java:290)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.propagateInternal(DPLLEngine.java:237)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.quickCheck(DPLLEngine.java:1691)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.assertTerm(SMTInterpol.java:656)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:2881)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:1311)
        at com.github.jhoenicke.javacup.runtime.LRParser.parse(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:154)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:133)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:37)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:180)

```
Script: 
[32_7_cilled_const_ok_linux-32_1-drivers--net--wireless--p54--p54usb.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i_AllErrorsAtOnce_Iteration6.smt2.txt](https://github.com/ultimate-pa/smtinterpol/files/4436161/32_7_cilled_const_ok_linux-32_1-drivers--net--wireless--p54--p54usb.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i_AllErrorsAtOnce_Iteration6.smt2.txt)

I can generate 11 more scripts from different files if necessary.

**Comment by jhoenicke** [comment]
This seems to be fixed by aad3127.
