### ISSUE TITLE
AssertionError in Clausifier.createLinVar

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/smtinterpol#61]
Attached script throws assertion error when assertions are enabled (java -ea -jar smtinterpol-2.5-638-g686b1653.jar).

Stack trace:
```
Exception in thread "main" java.lang.AssertionError
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.createLinVar(Clausifier.java:1114)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.EqualityProxy.createAtom(EqualityProxy.java:154)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.EqualityProxy.getLiteral(EqualityProxy.java:186)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.EqualityProxy.createCCEquality(EqualityProxy.java:109)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCTerm.propagateSharedEquality(CCTerm.java:262)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCTerm.share(CCTerm.java:238)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CClosure.addSharedTerm(CClosure.java:772)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.share(Clausifier.java:1003)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.shareLATerm(Clausifier.java:1011)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.createLinVar(Clausifier.java:1121)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.createMutableAffinTerm(Clausifier.java:1131)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.addTermAxioms(Clausifier.java:1076)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.EqualityProxy.createAtom(EqualityProxy.java:141)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.EqualityProxy.getLiteral(EqualityProxy.java:186)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier$CollectLiteral.perform(Clausifier.java:585)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.run(Clausifier.java:1879)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.addFormula(Clausifier.java:1946)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.assertTerm(SMTInterpol.java:650)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.InterpolantChecker.checkFinalInterpolants(InterpolantChecker.java:426)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.getInterpolants(Interpolator.java:221)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:866)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:2947)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:1311)
        at com.github.jhoenicke.javacup.runtime.LRParser.parse(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:154)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:133)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:37)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:180)
```
Script: 
[list_search-2.i_AllErrorsAtOnce_Iteration12.smt2.txt](https://github.com/ultimate-pa/smtinterpol/files/4436204/list_search-2.i_AllErrorsAtOnce_Iteration12.smt2.txt)

I can generate 2 more scripts if necessary.

**Comment by jhoenicke** [comment]
Fixed.

I'm not completely happy with the code.  At some time, we may need to rewrite the clausifier to create CC and LA terms in a better way.
