### ISSUE TITLE
NullPointerException or NegativeArraySizeException

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/smtinterpol#71]
Attached script is from an Ultimate run that threw the following exception.

Stack trace:
```
java.lang.NullPointerException
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.SimpleListable.removeFromList(SimpleListable.java:64)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCTermPairHash.removePairInfo(CCTermPairHash.java:119)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CClosure.removeTerm(CClosure.java:1252)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CClosure.pop(CClosure.java:1267)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.pop(DPLLEngine.java:1458)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.convert.Clausifier.pop(Clausifier.java:1998)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.pop(SMTInterpol.java:424)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.InterpolantChecker.checkFinalInterpolants(InterpolantChecker.java:436)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.getInterpolants(Interpolator.java:221)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:866)
        at de.uni_freiburg.informatik.ultimate.logic.NoopScript.getInterpolants(NoopScript.java:385)
```

Running the script directly with SMTInterpol (java -ea -jar smtinterpol-2.5-646-ga8a78500.jar ...) yields
```
Unexpected Exception: java.lang.NegativeArraySizeException
(error "java.lang.NegativeArraySizeException")
```

Script: 
[mapsum5.i_AllErrorsAtOnce_Iteration6.smt2.txt](https://github.com/ultimate-pa/smtinterpol/files/4480252/mapsum5.i_AllErrorsAtOnce_Iteration6.smt2.txt)

**Comment by jhoenicke** [comment]
The problem is caused by bad hashcodes:

```java
System.err.println(new java.math.BigInteger("-4294967295").hashCode())
1
```

So every term where you replace 1 by 2^32-1 has the same hash. Unfortunately it is not unlikely that many such terms exists.  This leads to an OutOfMemoryError as the CuckooHash can't handle more than three elements with exactly the same hash code.

The OutOfMemoryError aborts the current merge, which leads to an error in unmerge with the next pop.
